import NerdIcon from "./NerdIcon";

const ZMK_KEYCODE_MAP = {
	// Basic Keys
	'DOT': { text: '.', html: '.' },
	'FSLH': { text: '/', html: '/' },
	'SEMI': { text: ';', html: ';' },
	'SQT': { text: "'", html: "'" },
	'GRAVE': { text: "`", html: "`" },
	'LBKT': { text: '[', html: '[' },
	'RBKT': { text: ']', html: ']' },
	'DLLR': { text: '$', html: '$' },
	'PIPE': { text: '|', html: '|' },
	'EXCL': { text: '!', html: '!' },
	'AT': { text: '@', html: '@' },
	'HASH': { text: '#', html: '#' },
	'PLUS': { text: '+', html: '+' },
	'MINUS': { text: '-', html: '-' },
	'EQL': { text: '=', html: '=' },
	'LPAR': { text: '(', html: '(' },
	'RPAR': { text: ')', html: ')' },
	'PRCNT': { text: '%', html: '%' },
	'LBRC': { text: '{', html: '{' },
	'RBRC': { text: '}', html: '}' },
	'CARET': { text: '^', html: '^' },
	'AMPS': { text: '&', html: '&' },
	'STAR': { text: '*', html: '*' },
	'BSLH': { text: '\\', html: '\\' },

	// Special Keys with Nerd Fonts
	'ESC': { html: NerdIcon({ iconName: 'nf-md-keyboard_esc' }) },
	'TAB': { html: NerdIcon({ iconName: 'nf-md-keyboard_tab' }) },
	'ENTER': { html: NerdIcon({ iconName: 'nf-md-keyboard_return' }) },
	'RET': { html: NerdIcon({ iconName: 'nf-md-keyboard_return' }) },
	'SPACE': { html: NerdIcon({ iconName: 'nf-md-keyboard_space' }) },
	'LT_SPC': { html: NerdIcon({ iconName: 'nf-md-keyboard_space' }) },
	'BSPC': { html: NerdIcon({ iconName: 'nf-md-backspace' }) },
	'DEL': { html: NerdIcon({ iconName: 'nf-md-backspace_reverse' }) },
	'INS': { text: 'Ins', html: 'Ins' },
	'COMMA_MORPH': { text: ', ;', html: ', ;' },
	'DOT_MORPH': { text: '. :', html: '. :' },
	'QEXCL': { text: '? !', html: '? !' },
	// Navigation
	'HOME': { html: NerdIcon({ iconName: 'nf-md-home' }) },
	'END': { html: NerdIcon({ iconName: 'nf-md-end' }) },
	'PG_UP': { html: NerdIcon({ iconName: 'nf-md-arrow_up_bold_box' }) },
	'PG_DN': { html: NerdIcon({ iconName: 'nf-md-arrow_down_bold_box' }) },
	'UP': { html: NerdIcon({ iconName: 'nf-md-arrow_up' }) },
	'DOWN': { html: NerdIcon({ iconName: 'nf-md-arrow_down' }) },
	'LEFT': { html: NerdIcon({ iconName: 'nf-md-arrow_left' }) },
	'RIGHT': { html: NerdIcon({ iconName: 'nf-md-arrow_right' }) },

	// Modifiers
	'LSHFT': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_shift' }) },
	'RSHFT': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_shift' }) },
	'LCTRL': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_control' }) },
	'RCTRL': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_control' }) },
	'LALT': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_option' }) },
	'RALT': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_option' }) },
	'LGUI': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_command' }) },
	'RGUI': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_command' }) },

	// Bluetooth
	'BT': { html: NerdIcon({ iconName: 'nf-md-bluetooth' }) },
	'BT_SEL': { html: NerdIcon({ iconName: 'nf-md-bluetooth_connect' }) },
	'BT_CLR': { html: NerdIcon({ iconName: 'nf-md-bluetooth_off' }) },

	// Media & Control
	'C_PREV': { html: NerdIcon({ iconName: 'nf-md-skip_previous' }) },
	'C_NEXT': { html: NerdIcon({ iconName: 'nf-md-skip_next' }) },
	'C_VOL_UP': { html: NerdIcon({ iconName: 'nf-md-volume_high' }) },
	'C_VOL_DN': { html: NerdIcon({ iconName: 'nf-md-volume_medium' }) },
	'C_MUTE': { html: NerdIcon({ iconName: 'nf-md-volume_off' }) },
	'C_PP': { html: NerdIcon({ iconName: 'nf-md-play_pause' }) },
	'C_PLAY_PAUSE': { html: NerdIcon({ iconName: 'nf-md-play_pause' }) },
	'C_AC_SEARCH': { html: NerdIcon({ iconName: 'nf-md-magnify' }) },
	'C_AC_DESKTOP_SHOW_ALL_APPLICATIONS': { html: NerdIcon({ iconName: 'nf-md-view_dashboard' }) },
	'C_AC_DESKTOP_SHOW_ALL_WINDOWS': { html: NerdIcon({ iconName: 'nf-md-microsoft_windows' }) },

	// System
	'RESET': { html: NerdIcon({ iconName: 'nf-md-restart' }) },
	'SYS_RESET': { html: NerdIcon({ iconName: 'nf-md-restart' }) },
	'BOOTLOADER': { html: NerdIcon({ iconName: 'nf-md-chip' }) },
	'K_CANCEL': { html: NerdIcon({ iconName: 'nf-md-cancel' }) },

	// Numbers
	'N0': { text: '0', html: '0' },
	'N1': { text: '1', html: '1' },
	'N2': { text: '2', html: '2' },
	'N3': { text: '3', html: '3' },
	'N4': { text: '4', html: '4' },
	'N5': { text: '5', html: '5' },
	'N6': { text: '6', html: '6' },
	'N7': { text: '7', html: '7' },
	'N8': { text: '8', html: '8' },
	'N9': { text: '9', html: '9' },

	// Function Keys
	'F1': { text: 'F1', html: 'F1' },
	'F2': { text: 'F2', html: 'F2' },
	'F3': { text: 'F3', html: 'F3' },
	'F4': { text: 'F4', html: 'F4' },
	'F5': { text: 'F5', html: 'F5' },
	'F6': { text: 'F6', html: 'F6' },
	'F7': { text: 'F7', html: 'F7' },
	'F8': { text: 'F8', html: 'F8' },
	'F9': { text: 'F9', html: 'F9' },
	'F10': { text: 'F10', html: 'F10' },
	'F11': { text: 'F11', html: 'F11' },
	'F12': { text: 'F12', html: 'F12' },

	// macOS Specific
	'MAC_LP': { html: NerdIcon({ iconName: 'nf-md-view_dashboard' }) },
	'MAC_MC': { html: NerdIcon({ iconName: 'nf-md-desktop_mac_dashboard' }) },
	'MAC_SP': { html: NerdIcon({ iconName: 'nf-md-magnify' }) },
	'MAC_DKTP': { html: NerdIcon({ iconName: 'nf-md-arrow_left_bold_box' }) },
	'MAC_DKTN': { html: NerdIcon({ iconName: 'nf-md-arrow_right_bold_box' }) },
	'MAC_WINP': { html: NerdIcon({ iconName: 'nf-md-window_minimize' }) },
	'MAC_WINN': { html: NerdIcon({ iconName: 'nf-md-window_maximize' }) },
	'MAC_APPWIN': { html: NerdIcon({ iconName: 'nf-md-application' }) },
	'MAC_UNDO': { html: NerdIcon({ iconName: 'nf-md-undo' }) },
	'MAC_REDO': { html: NerdIcon({ iconName: 'nf-md-redo' }) },
	'MAC_COPY': { html: NerdIcon({ iconName: 'nf-md-content_copy' }) },
	'MAC_PASTE': { html: NerdIcon({ iconName: 'nf-md-content_paste' }) },
	'MAC_CUT': { html: NerdIcon({ iconName: 'nf-md-content_cut' }) },
	'MAC_FIND_NEXT': { html: NerdIcon({ iconName: 'nf-md-page_next' }) },
	'MAC_FIND_PREVIOUS': { html: NerdIcon({ iconName: 'nf-md-page_previous' }) },
	'MAC_NEXT_WORD': { text: 'Word→', html: 'Word→' },
	'MAC_PREVIOUS_WORD': { text: 'Word←', html: 'Word←' },
	'MAC_START_OF_LINE': { html: NerdIcon({ iconName: 'nf-md-home' }) },
	'MAC_END_OF_LINE': { html: NerdIcon({ iconName: 'nf-md-end' }) },

	// Mouse & Joystick
	'U_MS_U': { html: NerdIcon({ iconName: 'nf-md-mouse_move_up' }) },
	'U_MS_D': { html: NerdIcon({ iconName: 'nf-md-mouse_move_down' }) },
	'U_MS_L': { html: NerdIcon({ iconName: 'nf-md-mouse_move_left' }) },
	'U_MS_R': { html: NerdIcon({ iconName: 'nf-md-mouse_move_right' }) },
	'U_WH_U': { html: NerdIcon({ iconName: 'nf-md-mouse_scroll_up' }) },
	'U_WH_D': { html: NerdIcon({ iconName: 'nf-md-mouse_scroll_down' }) },
	'U_BTN1': { html: NerdIcon({ iconName: 'nf-md-cursor_default_click' }) },
	'U_BTN2': { html: NerdIcon({ iconName: 'nf-md-cursor_default_click_outline' }) },
	'U_BTN3': { html: NerdIcon({ iconName: 'Btn3' }) },
	'LCLK': { html: NerdIcon({ iconName: 'nf-md-cursor_default_click' }) },
	'RCLK': { html: NerdIcon({ iconName: 'nf-md-cursor_default_click_outline' }) },
	'MCLK': { html: NerdIcon({ iconName: 'nf-md-cursor_default_click' }) },
	'MKP': { html: NerdIcon({ iconName: 'nf-md-cursor_default_click_outline' }) },

	// RGB
	'CRGB_ON': { html: NerdIcon({ iconName: 'nf-md-lightbulb_on' }) },
	'CRGB_OFF': { html: NerdIcon({ iconName: 'nf-md-lightbulb_off' }) },
	'CRGB_HUI': { text: 'H+', html: 'H+' },
	'CRGB_HUD': { text: 'H-', html: 'H-' },
	'CRGB_SAI': { text: 'S+', html: 'S+' },
	'CRGB_SAD': { text: 'S-', html: 'S-' },
	'CRGB_BRI': { text: 'B+', html: 'B+' },
	'CRGB_BRD': { text: 'B-', html: 'B-' },
	'CRGB_SPI': { text: 'SP+', html: 'SP+' },
	'CRGB_SPD': { text: 'SP-', html: 'SP-' },
	'CRGB_EFF': { html: NerdIcon({ iconName: 'nf-md-palette' }) },
	'CRGB_EFR': { html: NerdIcon({ iconName: 'nf-md-palette_outline' }) },

	'SWAPPER': { html: NerdIcon({ iconName: 'nf-cod-multiple_windows' }) },
	'MT_HOME': { html: NerdIcon({ iconName: 'nf-md-arrow_left' }) },
	'DOWN': { html: NerdIcon({ iconName: 'nf-md-arrow_left' }) },
	'MT_END': { html: NerdIcon({ iconName: 'nf-md-arrow_right' }) },
	'SL': { text: 'SL', html: 'SL' },
	'LT': { text: 'LT', html: 'LT' },
	'MO': { text: 'MO', html: 'MO' },
	'TG': { text: 'TG', html: 'TG' },
	'TO': { text: 'TO', html: 'TO' },
	'TT': { text: 'TT', html: 'TT' },
	'LEADER': { text: 'LEAD', html: 'LEAD' },
	'DE_AE': { text: 'ä', html: 'ä' },
	'EL_ALPHA': { text: 'α', html: 'α' },
	'VOL_INCDEC': { html: NerdIcon({ iconName: 'nf-md-volume_source' }) },
	'INC_DEC_KP': { html: NerdIcon({ iconName: 'nf-md-volume_source' }) },
	'NONE': { text: '', html: '', icon: null },
	'TRANS': { text: '', html: '', icon: null },

	'MAGIC_SHIFT': {
		html: NerdIcon({ iconName: 'nf-md-apple_keyboard_shift' })
	},
	'SMART_NUM': {
		html: NerdIcon({ iconName: 'nf-md-format_list_numbered' })
	},
};

const MOD_ICON_MAP = {
	'LS': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_shift' }) },
	'RS': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_shift' }) },
	'LA': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_option' }) },
	'RA': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_option' }) },
	'LG': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_command' }) },
	'RG': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_command' }) },
	'LC': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_control' }) },
	'RC': { html: NerdIcon({ iconName: 'nf-md-apple_keyboard_control' }) },
};

export { ZMK_KEYCODE_MAP, MOD_ICON_MAP };
